### PR TITLE
Check if `atime` Date object is invalid and set a new one explicitly

### PR DESCRIPTION
**Pull request by piranna**
This fixes issue #118

### CODE REVIEW

**Comment by erikkemperman** [comment]
@piranna 
Sorry, looks like I searched the issues but not the PRs. Now my PR [here](https://github.com/gulpjs/vinyl-fs/pull/125) conflicts with yours... Might something like [this](https://github.com/erikkemperman/vinyl-fs/tree/fix-subsecond-precision-2) consolidate things, you think?

**Comment by phated** [comment]
@erikkemperman i can merge this and then you can rebase, thoughts?

**Comment by erikkemperman** [comment]
@phated Sure, rebasing is no problem. But perhaps @piranna should take a look at [this](https://github.com/erikkemperman/vinyl-fs/commit/3c0a040444577032444d65d35d7b739b1a085e3f) first?

**Comment by phated** [comment]
? I just merged @piranna's PR so you shouldn't need to consolidate, just resolve your changes now

**Comment by piranna** [comment]
Thanks for merging :-)

**Comment by phated** [comment]
@piranna no problem, I'm not sure how I missed this

**Comment by piranna** [comment]
Probably too much emails :-P It sometimes happens to me.

**Comment by erikkemperman** [comment]
@phated It's late where I am, I'd missed that you already merged this one... Rebased my PR just now.
@piranna As you were ;-)

**Comment by piranna** [comment]
;-)

**Pull request merged**
