### PR TITLE
Options refactor

### PR DESCRIPTION
**Pull request by erikkemperman**
Cleaned up (IMHO) options handling slightly, in particular prevent users accidentally doing something odd with `flag`. Also, added an `append` option (which I think might come in handy for things like build logs).

### CODE REVIEW

**Comment by phated** [comment]
@erikkemperman so this takes away the ability to use `r`, `r+`, `w+`, etc?

**Comment by erikkemperman** [comment]
Well, yes. None of those make sense in `dest`, do they? The file descriptor is always closed after (exclusively) writing or appending to it. The `flags` option was undocumented, and I figured my change only made explicit (and with clearer semantics than `flags`, IMHO) the already implemented ability to handle `a` in addition to `w`.

But if you expect some of those other flags might ever be useful, that's fine obviously; but I'd say it ought to be documented then?

**Comment by phated** [comment]
@erikkemperman you are right and I don't think the `flags` option was exposed until our options changes.  I was just making sure it takes those away because they are still being tested for the utils.  I **really**, **really** want to factor the utils into their own modules :frowning_face:

**Comment by phated** [comment]
@erikkemperman can you rebase this on top of the changes from the symlink/junction refactor (in master now)?  Thanks.

**Comment by erikkemperman** [comment]
@phated Done!

**Comment by phated** [comment]
Thanks @erikkemperman - This is great!  I've merged with a rebase to change some of the commit messages.

**Comment by phated** [comment]
On second thought, I might squash those all into 1

**Pull request closed without merging**
