### PR TITLE
sending options to throughjs via viny-js dest() 

### PR DESCRIPTION
**Pull request by vineethawal**
for sending options like "**highWaterMark**"(imp to specify buffer length) to throughtjs via vinyl-js dest()

**Issue**: Default highWaterMark value is 16(max buffer length), when default buffer length exceeds all files are not copied by dest

### CODE REVIEW

**Comment by phated** [comment]
The 0.3.14 branch is feature locked.

**Comment by vineethawal** [comment]
gulp is currently using vinyl-fs 0.3.14, this issue has been resolved in v2.x

**Comment by phated** [comment]
You can use vinyl-fs 2.x directly in your gulpfile

**Comment by vineethawal** [comment]
yup doin that, thanx? :)

**Comment by contra** [comment]
@phated What's the reasoning behind closing this?

**Comment by vineethawal** [comment]
@phated but this will continue to remain a bug in gulp 3.x

**Comment by phated** [comment]
Not a bug and actually a breaking change. Return your streams so they are sunk

**Comment by contra** [comment]
@phated Breaking change has nothing to do with merging PRs

**Comment by phated** [comment]
To clarify: 0.3.14 was tagged out of band to remove the engineStrict flag.  Merging these to master is not going to work.  The 0.3.x branch has long been surpassed by 1.x and 2.x (current) and they can be used directly for people that want the new stuff (and breaking changes).  The options are being passed in the 2.x branch so this is a non-issue.

**Comment by contra** [comment]
@phated Thanks for clarifying 👍

**Pull request closed without merging**
