### PR TITLE
Read-contents/index, invoke cb with error or result, not both

### PR DESCRIPTION
**Pull request by erikkemperman**
Separate PR, as per @phated's comment on https://github.com/gulpjs/vinyl-fs/pull/257.

### CODE REVIEW

**Comment by phated** [comment]
Thanks @erikkemperman

**Comment by phated** [comment]
@erikkemperman There seems to have been a race condition with node 0.10 on this change.  Not sure why but I re-ran and it passed.

**Comment by erikkemperman** [comment]
@phated That's weird -- I don't see how this little change would do that... Do you have logs so I can take a peek? I've run the test suite a couple of times with 0.10.0 and 0.10.48 but haven't been able to reproduce it here (Linux).

**Comment by phated** [comment]
Doesn't look like travis gives me access to the old logs of a restarted job.  It was something with a file descriptor being undefined when we expected it to be defined.  I'll keep an eye out in the future.

**Pull request merged**
