### PR TITLE
Breaking: Remove ability to pass options to through2

### PR DESCRIPTION
**Pull request by phated**
Opening for visibility.  I've fixed the non-sinking problems which were the whole reason for this "feature".

@erikkemperman this is how I'm going to handle our `read` option problem.

### CODE REVIEW

**Comment by erikkemperman** [comment]
Looks good to me, but then I have no idea why this was supported in the first place :-)

**Comment by phated** [comment]
I can explain it but I'm afk today.

**Comment by erikkemperman** [comment]
Never mind, no worries -- from where I'm standing it's just good to lose that ugly hack around `read`.

**Comment by phated** [comment]
I amended my commit and merged locally.

**Pull request closed without merging**
