### PR TITLE
Fix: Marshall old Vinyl objects to new Version in dest()

### PR DESCRIPTION
**Pull request by phated**
@erikkemperman @asgoth @stevelacy @doowb What do y'all think of this as the solution to #288 and gulpjs/gulp/issues/2065

### CODE REVIEW

**Comment by doowb** [comment]
@phated LGTM! I like that a new Vinyl instance is created only when an old Vinyl instance is detected.

**Comment by erikkemperman** [comment]
Not sure if we call `isSymbolic()` there, but if so should this be done for `symlink` and even `src` as well? And perhaps add a comment that this is to deal with out-of-date plugins and hopefully could be removed at some point?

**Comment by stevelacy** [comment]
I do also agree with @erikkemperman relating to also check/modify `symlink`. The rest looks good

**Comment by phated** [comment]
@erikkemperman @stevelacy I've added the marshalling to `.symlink` but I don't think it's necessary because we don't check `.isSymbolic()` in that API - (`.src` actually always marshalls in the `wrap-file` stream).  I've also added erik's requested TODO.

**Comment by erikkemperman** [comment]
@phated Looks good to me, thanks!

**Comment by phated** [comment]
@erikkemperman @doowb @stevelacy Thanks for reviewing this!

**Pull request merged**
