### PR TITLE
Refactor prepare read

### PR DESCRIPTION
**Pull request by erikkemperman**
@phated 
Ref https://github.com/erikkemperman/vinyl-prepare/commit/3558db36478500d5508431b751947d7444003d8a#commitcomment-21860733

This is the counterpart to https://github.com/gulpjs/vinyl-prepare/pull/11.

I've rebased your latest version of the prepare-stream branch onto latest master and then bolted my work on top of that. Took some doing, at first I didn't notice you had considerably altered your "split prepareWrite" commit.

It won't merge automatically, but the idea is my branch could be a drop-in replacement for prepare-stream.

### CODE REVIEW

**Comment by phated** [comment]
Thanks.  I'm having a really hard time thinking that vinyl-prepare is worth the effort because it feels like a very leaky abstraction (especially when I try to implement sourcemaps into it).  I'm currently letting my subconscious solve it 😛

**Comment by erikkemperman** [comment]
I don't know -- the original use case for it still seems valid, "dry run dest" if memory serves. And it unclutters vinyl-fs slightly. 

Anyway, if your subconscious decides against the split please do let me know... I've ended up conflating a bunch of issues here, and might try separating out the other bits (function-values for options, rename followSymlinks, symmetrical directory layout).

**Comment by phated** [comment]
That use case is still valid but the sourcemaps logic adds filesystem operations.  Maybe it makes better sense to keep `vinyl-prepare` without sourcemaps and integrate them in vinyl-fs directly.

**Comment by erikkemperman** [comment]
I understand about keeping file ops out of vinyl-prepare. Just out of curiosity, what kind of trouble are you running into with sourcemaps? For what it's worth I changed essentially nothing around sourcemaps because I knew you were working on https://github.com/gulpjs/vinyl-sourcemap.

**Comment by erikkemperman** [comment]
Cool, I did not know I could resolve merge conflicts on a PR in the github webinterface!

**Comment by phated** [comment]
@erikkemperman oops, I just made everything real awkward with this merge because I rebased `prepare-stream` branch with master.  Can you rebase again?

**Comment by phated** [comment]
Actually, can you split the non-`prepare-write` changes into separate PRs?  I'd like to get those landed separately (automated changelog)

**Comment by phated** [comment]
I'm actually just going to cherrypick them into master because I drank a lot of coffee today and am very impatient 😛

**Comment by phated** [comment]
I believe I have this fully cherry-picked into the proper branches (wasn't as easy as I thought it would be) and passing CI.

**Comment by phated** [comment]
As always, many thanks @erikkemperman

**Comment by erikkemperman** [comment]
Thanks for moving this along!

**Pull request closed without merging**
