### PR TITLE
Don't pass `read` option from `src` to `through2`

### PR DESCRIPTION
**Pull request by erikkemperman**
As promised in [#153](https://github.com/gulpjs/vinyl-fs/issues/153)

### CODE REVIEW

**Comment by phated** [comment]
@erikkemperman can you add a test for this?  I'm not sure the behavior passing it caused

**Comment by erikkemperman** [comment]
I'm not sure what it would test...? What I noticed is if I pass a function to the `read` option of `src` -- expecting its boolean return value to be used to determine whether or not to read the file contents -- it was instead being treated as the `read` implementation of stream, because it is passed on to `through2`.

So I suppose I could write a test that does that and check that the function is not called (that my PR makes sure it's not passed to through2). But you mentioned that function values are going to be supported soon, so then this test would be in the way.

Anyway, the diff is pretty self-evidently doing what it advertises, I thought?

**Comment by phated** [comment]
Yeah, I just would like some sort of test so I don't add a regression during a refactor. I actually tried refactoring my other PR today but all the tests caught my mistakes and I realized I couldn't do what I was trying. I'd be happy with the test suggestion you made, it shouldn't be in the way.

**Comment by erikkemperman** [comment]
All right, will do. I'll add a comment though because I do expect this test might confuse whoever ends up implementing function-value support for options like `read` and `buffer`.

**Comment by erikkemperman** [comment]
@phated Rebased and added the requested test, with comment on how to tweak it if/when function-values for options like `read` are supported. You can make it fail by removing line [48](https://github.com/erikkemperman/vinyl-fs/commit/3b67921fe5ddd925fc12acef2bd03777b0081dc3#diff-2599ed3c945bd61f0161c2419a569f0bR48) from src/index.js.

**Comment by phated** [comment]
Thanks @erikkemperman!  Published as 2.4.1 (those travis tests took forever)

**Pull request merged**
