### PR TITLE
Update: Support `encoding` option

### PR DESCRIPTION
**Pull request by erikkemperman**
Re-submit: I've squashed my commits into a single one, and grafted it onto the new master.
Ref. https://github.com/gulpjs/vinyl-fs/pull/257

### CODE REVIEW

**Comment by erikkemperman** [comment]
Appveyor build is stuck, closing and re-opening PR to trigger another.

**Comment by erikkemperman** [comment]
FYI Rebased this and bumped the `iconv-lite` dependency to latest release.

@phated In the other thread you mentioned having ideas to improve this, e.g. [here](https://github.com/gulpjs/vinyl-fs/pull/257#issuecomment-315469843). I'd love to eventually get encoding support in a next release, would you have some time for a little more back-and-forth to get this feature ready?

**Comment by phated** [comment]
@erikkemperman I don't actually remember what I was thinking there but I really want to land this for an upcoming version.  I know you've done a lot of work here so I want to dedicate some time to reviewing/suggesting things before I start my new gig mid-June.

**Comment by erikkemperman** [comment]
Rebased and upgraded `iconv-late` to latest.

**Comment by erikkemperman** [comment]
I guess landing this would also involve adding some docs to the main gulp repo, once your major documentation effort over there settles.

**Comment by phated** [comment]
@erikkemperman I just want to say that you did amazing work on this PR and I have let it sit for far too long. I'm going to merge this as a "Breaking" feature so we can get batched in the big vinyl-fs updates that will be happening soon.

🍻🍻🍻🍻

**Comment by erikkemperman** [comment]
@phated Oh wow, I had almost forgotten about this PR. Did it even merge easily still? That’s great, thanks a lot!

**Pull request merged**
