### PR TITLE
Issue #1273 (gulp queue): Gulp.src() doesn't follow symlinks

### PR DESCRIPTION
**Pull request by OnkelTem**

### CODE REVIEW

**Comment by Klowner** [comment]
does `followSymlinks: false` option not accomplish this?

**Comment by phated** [comment]
As @Klowner stated, I think that options covers this use case

**Comment by phated** [comment]
We have tests for this expected behavior and it is documented.  I don't think we should merge this.

**Comment by OnkelTem** [comment]
As you can see from the code:

```js
function resolveSymlinks(options) {

  // a stat property is exposed on file objects as a (wanted) side effect
  function resolveFile(globFile, enc, cb) {
    fs.lstat(globFile.path, function (err, stat) {
      if (err) {
        return cb(err);
      }

      globFile.stat = stat;

      if (!stat.isSymbolicLink() || !options.followSymlinks) {
        return cb(null, globFile);
      }
      ...
```
if `followSymlinks` is `false` then no symlink resolution is made and then happens what is described here: https://github.com/gulpjs/gulp/issues/1273

**Comment by OnkelTem** [comment]
Also, tests have issues. Give me some time, I'll prepare a PR.

**Comment by Klowner** [comment]
You mention permissions in #1273, is the issue you're having with vinyl keeping symlink permissions or am I misunderstanding?

**Comment by phated** [comment]
I believe this is solved properly in #131 so I'm going to close this.

**Pull request closed without merging**
