### PR TITLE
Add documentation for `dot` option

### PR DESCRIPTION
**Pull request by matthewmueller**
Available in gulp-stream, but not documented here.

### CODE REVIEW

**Comment by contra** [comment]
@matthewmueller +1 for consolidating our documentation, we link to other docs too often and it's become a mess. Every README should contain all of the information all the time, we punted a lot with "See (x other project) README for other options you can use"

**Comment by matthewmueller** [comment]
haha yah +1, i actually didn't even notice the other links until you mentioned them

**Comment by contra** [comment]
@matthewmueller I've seen you submit some PRs over the last while, would you be interested in joining the org to help out with issues/documentation?

**Comment by matthewmueller** [comment]
@contra happy to help where i can, though i'm not sure i'll have much time. 

i'm using vinyl-fs in 2 pretty big projects, so if i run into any snags, i'll try and make it easier for future devs and future me.

**Pull request merged**
