### PR TITLE
#210 Fix Windows symbolic links requiring admin

### PR DESCRIPTION
**Pull request by afinnell**
Default to junctions instead of dir on windows unless told otherwise.

### CODE REVIEW

**Comment by contra** [comment]
Tests are failing ^

**Comment by phated** [comment]
@afinnell any progress on getting the tests to pass?

**Comment by afinnell** [comment]
My apologies. This notification became swept up in the wrong folder. I'll take a look.

**Comment by afinnell** [comment]
@phated I believe I've fixed the errors now that I see what they were. I feel slightly silly but it doesn't appear that GitHub has an easy way to update an existing Pull Request with an additional commit. 

Should I rebase the commits in this branch and push it back or will that break the CI server since it's already cloned the repo and checked out the branch? I can close the PR and create a new one if that's an easier solution.

**Comment by phated** [comment]
You can just push the commit and it will be added to the PR. Rebase also works

**Comment by afinnell** [comment]
So I don't think Test "symlink stream can create relative links for directories:" is going to work with the junctions. I'll change the logic around to support junctions instead of them being the default. This way the tests stay the same and no one is impacted. however, I still don't understand how these tests even pass unless they are ran as the Administrator or as a User that is not in the Administrators group. 

I'm beginning to think that running as a User who is in the Administrator group is not the way other developers run on Windows. Not running as Administrator User, but as a User in the Administrator group. The OS Kernel hard stops ANY User that is in the Administrator group from creating symlinks and there is no setting I can find to change this. Now if I create a dummy account that is not in the Administrators group then I can create symlinks. This is all backwards in my mind and wouldn't mind someone explaining this logic to me. 

I'll post the update shortly.

**Comment by afinnell** [comment]
Here is some irony for anyone following the ticket:

If one were to use Bash for Windows, and create a symbolic link using the `ln -s` command in a Bash shell, it shows up as a JUNCTION on Windows no matter what. Even if it's a symbolic link to a file. Which obviously doesn't work.

**Comment by phated** [comment]
Seems like a linting error crept in.  Please fix.

**Comment by afinnell** [comment]
Fixed lint errors again. Not sure how those spaces keep ending up on the end. Toughest lint rules I've ever seen, but makes for nice clean code. 

I also added a hard-link stream target and the mocha tests to follow.

**Comment by afinnell** [comment]
@phated @contra If everyone is comfortable with these changes (which should not break existing functionality / gulps) can we get this into the next release, asap? NPM doesn't make it easy to use your own version of a build. I realize it's possible, it's just not easy especially when you have a team. 

If this can't make it into the build that is not a problem, I just need to know so that I can create my own npm gulp module. 

My appreciation!

Andrew

**Comment by contra** [comment]
@afinnel you can put `"vinyl-fs": "afinnell/vinyl-fs"` in your package.json and it'll use your version

LGTM, but missing documentation

**Comment by afinnell** [comment]
@contra The wiki pages or the .MD files? Or both?

**Comment by contra** [comment]
@afinnel The README. Wasn't aware we had wiki pages (?), I thought i had disabled that on every repo since they are typically worse than just markdown files.

**Comment by contra** [comment]
@afinnell Correction: we don't have a wiki

image

**Comment by phated** [comment]
@afinnell I still have to review this but i wanted to let you know it will go in the 3.0 release because we have many breaking changes in the master branch and rebasing this into a different release would be a headache.  We still have a few things to get done before the 3.0 release.

**Comment by afinnell** [comment]
@phated Not a problem. After feeling ignorant and not realizing I could npm install afinnell/vinyl-fs I'm set. I can merge these changes into the 3.x mainline if you need me to. Even if it requires a rework, I can redo it once 3.x is stable. Thanks!

**Comment by phated** [comment]
I reviewed this and it looks good. I need to figure out exactly when I'm going to pull it in.  Thanks for all the work @afinnell

**Comment by phated** [comment]
@afinnell actually, can you squash the commits and rebase/cherry-pick onto master?  I've just done some rebasing to cleanup commits and it seems to have diverged your PR.  Thanks again.

**Comment by afinnell** [comment]
@phated Not a problem, it'll be my pleasure.

**Comment by K05** [comment]
@afinnell @phated wondering what is the status w/ this fix?

**Comment by phated** [comment]
Not even reviewed yet; there's too much else to work on. Looks like it still needs to be rebased and squashed, too.

**Comment by phated** [comment]
@afinnell I just rebased this and started to review.  It seems the wrong thing is being tested.  You added tests for `.src` reading the hardlinks but nothing where your new `.link` method is being used.

**Comment by afinnell** [comment]
I will look at my local repo and ensure the latest commits were pushed. Been out of hand and thus unresponsive. I appreciate the heads up on this.

**Comment by phated** [comment]
Solved by 5ae7d7e4c674cdd6bafd8d29eb332c0adbcb760b

**Pull request closed without merging**
